pipeline:
  test:
    image: golang:latest
    commands:
      - export GOPATH=/drone
      - export CGO_ENABLED=0
      - export PEBBLE_VA_ALWAYS_VALID=1
      - .drone/script
  doc:
    image: asciidoctor/docker-asciidoctor
    commands:
      - apk add --no-cache libxslt docbook-xsl
      - "(cd _doc/guide && make;)"
